name: sel_org
description: SelOrg.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  google_maps_flutter: ^2.6.1
  dropdown_button2: ^2.3.9
  flutter_google_places:
  connectivity_plus: ^4.0.1
  flutter_bloc: ^8.1.3
  flutter_svg:
  shared_preferences:
  equatable: ^2.0.5
  lottie: ^2.4.0
  pin_code_fields: ^8.0.1
  odometer: ^2.1.0
  image_picker: ^1.0.1
  permission_handler: ^10.4.3
  camera: ^0.10.5+2
  intl:
  flutter_native_splash: ^2.3.2
  get_it: ^7.2.0
  injectable: ^2.1.1
  flutter_html:
  firebase_messaging:
  firebase_core:
  flutter_pdfview: ^1.0.0
  pdf: ^3.10.4

  path_provider: ^2.0.5
  location: ^5.0.0
  mappls_gl: ^1.0.0
  mappls_place_widget: ^1.0.0
  mappls_direction_plugin: ^1.0.0
  mappls_nearby_plugin: ^1.0.0
  pinput: ^4.0.0
  package_info_plus: ^4.1.0
  dio:
  dio_http_cache:
  geocoding: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^4.0.4
#  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^4.2.1
  flutter_pannable_rating_bar: ^2.7.2+1
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  assets:
    - assets/svg/
    - assets/png/
    - assets/png/3star_rating_img/
    - assets/png/5star_rating_img/

  uses-material-design: true
  fonts:
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-MediumItalic
      fonts:
        - asset: fonts/Poppins-MediumItalic.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
